# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/market_state.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto/market_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/market_state.proto\x12\roptions_proxy\"\xf8\x01\n\x0eIndicatorFrame\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x1a\n\x12\x65mitted_at_unix_ms\x18\x02 \x01(\x03\x12\x0e\n\x06ticker\x18\x03 \x01(\t\x12!\n\x19static_daily_implied_move\x18\x04 \x01(\x01\x12\'\n\x1fstatic_daily_implied_move_valid\x18\x05 \x01(\x08\x12\x16\n\x0espy_gamma_flip\x18\x07 \x01(\x01\x12\x1c\n\x14spy_gamma_flip_valid\x18\x08 \x01(\x08\x12\x14\n\x0ctrading_date\x18\x0b \x01(\tJ\x04\x08\x06\x10\x07J\x04\x08\t\x10\nJ\x04\x08\n\x10\x0b\x42\x34\n\x1emwd.trading.optionsproxy.protoB\x10MarketStateProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.market_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036mwd.trading.optionsproxy.protoB\020MarketStateProtoP\001'
  _globals['_INDICATORFRAME']._serialized_start=44
  _globals['_INDICATORFRAME']._serialized_end=292
# @@protoc_insertion_point(module_scope)
